print("josh is a gay")
print("josh is a gay")
print("josh is a gay")  
print("josh is a gay")  
print("josh is a gay")  
print("josh is a gay")  
print("josh is a gay")
print("josh is a gay")
print("python")